// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com.grpc/AccountService.proto

package com.grpc;

public interface AccountOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.grpc.Account)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>double num = 2;</code>
   * @return The num.
   */
  double getNum();
}
